version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewExternalGitPProject
  gitServerName: testNewgit
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.newexternalgitp.integrations:edge1
  packages:
  - name: NewExternalGitPProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.1081
