version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewExternalGitPProject
  gitServerName: testNewgit
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
